/**
 * snapCX - Shippping Tracking API for commerce & retailers.
 * This API provides real time shipping tracking status (along with tracking events) for multiple carriers. It takes carrier code (UPS or USPS or FEDEX or DHL Or Canada Post) and tracking number as input. To invoke this API, you need to have your own private api key (aka user_key). You can always sign up for FREE plan to get user_key.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@snapcx.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.snapcx.tracking.client.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.snapcx.tracking.client.model.TrackEvent;
import io.snapcx.tracking.client.model.TrackSummary;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;


/**
 * TrackRecord
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-01-03T19:17:01.024-05:00")
public class TrackRecord   {
  @JsonProperty("trackSummary")
  private TrackSummary trackSummary = null;

  @JsonProperty("trackEvent")
  private List<TrackEvent> trackEvent = new ArrayList<TrackEvent>();

  public TrackRecord trackSummary(TrackSummary trackSummary) {
    this.trackSummary = trackSummary;
    return this;
  }

   /**
   * Get trackSummary
   * @return trackSummary
  **/
  @ApiModelProperty(example = "null", value = "")
  public TrackSummary getTrackSummary() {
    return trackSummary;
  }

  public void setTrackSummary(TrackSummary trackSummary) {
    this.trackSummary = trackSummary;
  }

  public TrackRecord trackEvent(List<TrackEvent> trackEvent) {
    this.trackEvent = trackEvent;
    return this;
  }

  public TrackRecord addTrackEventItem(TrackEvent trackEventItem) {
    this.trackEvent.add(trackEventItem);
    return this;
  }

   /**
   * Get trackEvent
   * @return trackEvent
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<TrackEvent> getTrackEvent() {
    return trackEvent;
  }

  public void setTrackEvent(List<TrackEvent> trackEvent) {
    this.trackEvent = trackEvent;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TrackRecord trackRecord = (TrackRecord) o;
    return Objects.equals(this.trackSummary, trackRecord.trackSummary) &&
        Objects.equals(this.trackEvent, trackRecord.trackEvent);
  }

  @Override
  public int hashCode() {
    return Objects.hash(trackSummary, trackEvent);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TrackRecord {\n");
    
    sb.append("    trackSummary: ").append(toIndentedString(trackSummary)).append("\n");
    sb.append("    trackEvent: ").append(toIndentedString(trackEvent)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

